Vagrant.configure("2") do |config|

  config.vm.define "source", autostart: false do |source|
	  source.vm.box = "#{ENV["SRC_IMAGE_NAME"]}"
    source.vm.box_version = "#{ENV["SRC_IMAGE_VERSION"]}"

    source.vm.provider "virtualbox" do |vb|
      vb.name = "{{.BoxName}}"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--memory", "4096" ]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize [
        "modifyvm", :id, "--uartmode1", "file",
        File.join(Dir.pwd, "ubuntu-bionic-18.04-cloudimg-console.log")
      ]    
      vb.customize ["modifyvm", :id, "--groups", "/basebox-build" ]
      vb.customize ["modifyvm", :id, "--vram", 256 ]
    end
    
	  config.ssh.insert_key = {{.InsertKey}}
  end

  config.vm.define "output" do |output|
	  output.vm.box = "{{.BoxName}}"
	  output.vm.box_url = "file://package.box"
	  config.ssh.insert_key = {{.InsertKey}}
  end

  config.vm.synced_folder "..", "/vagrant"

end