# test role for ubuntu
- src: http://vcs.corp.conextrade.com/conextrade-galaxy/ubuntu-test-role.git
  scm: git
  version: master
  name: ubuntu-test-role

# test role for win2012
- src: http://vcs.corp.conextrade.com/conextrade-galaxy/win2012-test-role.git
  scm: git
  version: master
  name: win2012-test-role
