Vagrant.configure("2") do |config|

    $basebox_name="basebox-ubuntu-18.04-k3s-test"
    $basebox_hostname="ubuntu-1804-k3s-test"
    $src_image_name="elegoev/ubuntu-18.04-docker"
    $src_image_version="3.0.1613669043"

    scriptlist = Array[]
    scriptlist = Dir.glob("../../packer/provisioners/*").sort    

    config.vm.define "#{$basebox_name}" do |machine|
      machine.vm.box = "#{$src_image_name}"
      machine.vm.box_version = "#{$src_image_version}"
    
      # define guest hostname
      machine.vm.hostname = "#{$basebox_hostname}"

      machine.vm.provider "virtualbox" do |vb|
        vb.name = $basebox_name
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--memory", "1024" ]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--groups", "/basebox-test" ]
        vb.customize ["modifyvm", :id, "--vram", 256 ]
      end

      # file provisioning
      machine.vm.provision "file", source: "../../packer/files-prov", destination: "/home/vagrant/files-prov"
      
      # shell provisioning
      scriptlist.each { |scriptpath|
        machine.vm.provision :shell do |cfg|
          cfg.name = File.basename(scriptpath)
          cfg.path = scriptpath
        end        
      }

    end   

end
  