Vagrant.configure("2") do |config|

  $basebox_name="basebox-ubuntu-18.04-k3s-test"
  $basebox_hostname="ubuntu-1804-k3s-test"
  $src_image_name="#{ENV["SRC_IMAGE_NAME"]}"
  $src_image_version="#{ENV["SRC_IMAGE_VERSION"]}"

  config.vm.define "#{$basebox_name}" do |machine|
    machine.vm.box = "#{$src_image_name}"
    machine.vm.box_version = "#{$src_image_version}"
    
    # define guest hostname
    machine.vm.hostname = "#{$basebox_hostname}"

    machine.vm.provider "virtualbox" do |vb|
      vb.name = $basebox_name
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--memory", "4096" ]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize [
        "modifyvm", :id, "--uartmode1", "file",
        File.join(Dir.pwd, "ubuntu-bionic-18.04-cloudimg-console.log")
      ]    
      vb.customize ["modifyvm", :id, "--groups", "/basebox-test" ]
      vb.customize ["modifyvm", :id, "--vram", 256 ]
    end
      
    # shell provisioning
    machine.vm.provision :shell do |cfg|
      cfg.name = "base-provisioning.sh"
      cfg.path = "../../packer/provisioners/base-provisioning.sh"
    end        

    machine.trigger.after :destroy do |trigger|
      trigger.info = "Cleanup environment"
      trigger.run = {path: "./cleanup-vagrant.ps1"}  
    end

  end   

end
  